name: health_plus
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6

  dio: ^5.4.3+1
  flutter_pretty_dio_logger: ^3.0.0
  google_fonts: ^6.2.1
  go_router: ^14.0.2
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  intl_utils: ^2.8.7
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.5
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  package_info_plus: ^8.0.0
  health: ^10.2.0
  fl_chart: ^0.67.0
  permission_handler: ^11.3.1
  custom_refresh_indicator: ^3.1.0
  provider: ^6.1.2
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  go_router_builder: ^2.6.1

flutter:
  uses-material-design: true
  assets:
      - assets/svg/
      - assets/icons/

flutter_intl:
  enabled: true
  main_locale: ru

flutter_gen:
  integrations:
    flutter_svg: true

flutter_launcher_icons:
  android: "ic_launcher"
  image_path: "assets/icons/icon.png"